// cmd/main.go
package main

import (
	"github.com/gorilla/handlers"
	"log"
	"net/http"
	"pokemon-service/config"
	"pokemon-service/middleware"
	"pokemon-service/routes"

	httpSwagger "github.com/swaggo/http-swagger"

	_ "pokemon-service/docs" // Import docs generated by Swag
)

// @title Pokemon API
// @version 1.0
// @description This is a sample Pokemon API using Golang.

// @host localhost:5000
// @BasePath /api

func main() {
	cfg := config.LoadConfig()
	router := routes.RegisterRoutes()

	// Apply logging middleware
	loggedRouter := middleware.LoggingMiddleware(router)

	// Enable CORS
	corsOptions := handlers.CORS(
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowedMethods([]string{"GET", "POST", "OPTIONS"}),
		handlers.AllowedHeaders([]string{"Content-Type"}),
	)

	//http://localhost:5000/swagger/index.html
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	log.Printf("Server running on IP %s port %s", cfg.Address, cfg.Port)
	if err := http.ListenAndServe(cfg.Address+":"+cfg.Port, corsOptions(loggedRouter)); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
} /*main()*/
