basePath: /api
definitions:
  models.Pokemon:
    properties:
      height:
        type: integer
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      stats:
        items:
          $ref: '#/definitions/models.Stat'
        type: array
      types:
        items:
          type: string
        type: array
      weight:
        type: integer
    type: object
  models.Stat:
    properties:
      name:
        type: string
      value:
        type: integer
    type: object
host: localhost:5000
info:
  contact: {}
  description: This is a sample Pokemon API using Golang.
  title: Pokemon API
  version: "1.0"
paths:
  /api/pokemon:
    get:
      consumes:
      - application/json
      description: Get a list of Pokémon with names and images.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Pokemon'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Pokémon List
      tags:
      - Pokémon
  /api/pokemon/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information about a Pokémon by ID.
      parameters:
      - description: Pokémon ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pokemon'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Pokémon Details
      tags:
      - Pokémon
swagger: "2.0"
